AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - "*.gemspec"
  - "spec/**/*.rb"

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 25

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
